---
- name: Manage Windows Service
  hosts: "{{ variable_host | default('all') }}"
  tasks:
  - name: Setting service state
    win_service:
      name: "{{ service_name | default('spooler') }}"
      state: "{{ service_state | default('started') }}"
