---
- name: Copy & Install Windows HotFixe
  hosts: all
  tasks:

    - name: Copy accross HotFixes 
      win_copy:
        src: /tmp/windows10.0-kb4465659-x64_af8e00c5ba5117880cbc346278c7742a6efa6db1.msu
        dest: C:\temp\windows10.0-kb4465659-x64_af8e00c5ba5117880cbc346278c7742a6efa6db1.msu
        force: no
  
    - name: Install hotfix validating KB
      win_hotfix:
        hotfix_kb: KB4465659
        state: present
        source: C:\temp\windows10.0-kb4465659-x64_af8e00c5ba5117880cbc346278c7742a6efa6db1.msu
      register: hotfix_install
