- name: Update a specific package
  hosts: all
  become: yes
  tasks:
    - name: Updating "{{package}}" to latest
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ package }}"
